### PR TITLE
Header

### PR DESCRIPTION
**Pull request by benjiatch**

### CODE REVIEW

**Review by StellaSFE96 — APPROVED** [review]

**Review by qimlonnegren — CHANGES_REQUESTED** [review]
Lägg till } på rad 167 på Header.

**Review by qimlonnegren — CHANGES_REQUESTED** [review]
Remove hero from accessories, ....

**Review by qimlonnegren — CHANGES_REQUESTED** [review]
Change name of export default on new views.

**Review by qimlonnegren — CHANGES_REQUESTED** [review]
Get more accessories, attire and skateboard items (cap, socks, totebag, hoodie, wheels, skateboards m.m.)

**Comment by qimlonnegren** [comment]
Insufficient.

**Pull request closed without merging**
